service: navixml

provider:
  name: aws
  runtime: java8

package:
  artifact: target/scala-2.12/navixml.jar

functions:
  hello:
    handler: onextent.hello.ScalaHandler::handle
  helloweb:
    handler: onextent.hello.ApiGatewayScalaHandler::handle
    events:
      - http:
          path: hello
          method: post
  xmltojson:
    handler: onextent.navixml.ApiGatewayPizzaXmlHandler::handle
    events:
      - http:
          path: pizza
          method: post

