service: navixml

provider:
  name: aws
  runtime: java8

package:
  artifact: target/scala-2.12/hello.jar

functions:
  hello:
    handler: hello.ScalaHandler::handle
  helloweb:
    handler: hello.ApiGatewayScalaHandler::handle
    events:
      - http:
          path: hello
          method: post
