service: navixml

provider:
  name: aws
  runtime: java8

package:
  artifact: target/scala-2.12/hello.jar

functions:
  hello:
    handler: hello.Handler
  helloScala:
    handler: hello.ScalaHandler::handle

